
#
# Server Properties
#
server:
  port: ${NOTIFICATION_SERVICE_SERVER_PORT}
  tomcat:
    accept-count: 100            # Keep or adjust based on load
    max-connections: 8192        # Max sockets Tomcat will accept (default: 8192)
    threads:
      max: 200                   # Max worker threads (default: 200)
      min-spare: 10              # Min threads kept alive (default: 10)
    connection-timeout: 5000

#
# Spring Properties
#
spring:
  application:
    name: notification-service

  #
  # Database Properties
  #
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        jdbc.batch_size: 30
        order_inserts: true
        order_updates: true
        generate_statistics: false
        format_sql: true

  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false

  #
  # Redis Properties
  #
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 2000
      lettuce:
        pool:
          max-active: 8
          max-idle: 4
          min-idle: 2
          max-wait: 2000
        shutdown-timeout: 100

  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      group-id: notification-service-group
      auto-offset-reset: latest
      enable-auto-commit: false
      properties:
        max.poll.records: 1000
        max.poll.interval.ms: 300000
        session.timeout.ms: 10000

app:
  kafka:
    topics:
      consumer:
        notifications: notifications.events
        notifications-dlq: notification.events.dlq

#
# Management Properties
#
management:
  server:
    port: ${server.port}
  endpoints:
    web:
      exposure:
        include: health, info, metrics, shutdown, prometheus
  endpoint:
    prometheus:
      enabled: true
    shutdown:
      enabled: true
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    metrics:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  health:
    redis:
      enabled: true
    db:
      enabled: true
    diskspace:
      enabled: true

#
# Spring Doc Properties
#
springdoc:
  api-docs:
    path: /api/docs/schema
    enabled: true
  swagger-ui:
    path: /api/docs/swagger-ui
    enabled: true

#
# Logging Properties
#
logging:
  level:
    root: info
    org.hibernate.SQL: debug
    com.finemeet.notification-service: debug