version: '3.8'

services:

  # 🐘 PostgreSQL
  postgres:
    image: postgres:16
    container_name: finemeet_postgres_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: finemeet_postgres
      POSTGRES_PASSWORD: finemeet_postgres
      POSTGRES_DB: user_service_postgres_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - finemeet-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finemeet"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 🧠 Redis (for caching)
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - finemeet-network
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 🛠️ pgAdmin (optional)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@finemeet.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - finemeet-network


networks:
  finemeet-network:
    driver: bridge

volumes:
  pgdata:
  redisdata:
